### ISSUE TITLE
[BUG] .lockOrientation is not applied to photo confirmation view

### ISSUE THREAD

**Issue by bogdan** [Mijick/Camera#70]
Photo confirmation view still remains vertically oriented after taking a picture with horizontal orientation:

![image](https://github.com/user-attachments/assets/6ec9c89e-c56d-4186-970a-a446d2ab1be1)

**Comment by FulcrumOne** [comment]
Hey @bogdan,

Thanks for this issue, it actually gave me some food for thought.

My idea for this method was to lock the screen orientation for the camera screen, so that all the controls don't wander all over the screen and cause too much noise. 
However, I do agree that the orientations of the captured media screen and error screen should not be locked, so I'm adding this ‘bug fix’ to the version 3.0.0, which will be released this week.

Thanks for your contribution,
Tomasz K.

**Comment by FulcrumOne** [comment]
Hey @bogdan,

The issue has been fixed in the branch `patch-3.0.0`.

Have a nice day,
Tomasz
