### ISSUE TITLE
[FREQ] Block Screen Rotation for MCameraController locks all view orientations

### ISSUE THREAD

**Issue by jamesbradleym** [Mijick/Camera#9]
Per the read.me: https://github.com/Mijick/CameraView?tab=readme-ov-file#4-optional-block-screen-rotation-for-mcameracontroller

It sounds as though _only_ the camera controller will be locked but actually setting `.lockOrientation(AppDelegate.self)` locks every other view as well if it is visible. This seems to be a particularly difficult issue to solve, locking a single view's orientation while allowing other views to freely rotate based on orientation of the device..

**Comment by FulcrumOne** [comment]
Hey @jamesbradleym,

Thanks for this comment. Unfortunately I hadn't thought of that case where other views not related to the camera view are also visible. 
Implementing it the way you described will be quite difficult, but could you show me the screen view you're trying to implement, then maybe I can come up with something 'creative'. Thanks again for discovering this problem and have a good day,
T.K.

**Comment by jamesbradleym** [comment]
It certainly seems to be, I haven't yet found a single solution which is why originally I made my own camera view before seeing your project which looks great. 

The use case is allowing users to, for example, use a top drawer that you can pull down (similar gesture as pulling down settings from the upper right of an iOS device) which contains additional settings (or in my case a music player controller which also includes a search feature for spotify, so it activates the keyboard which if the orientation is locked to portrait would mean the keyboard pops out from the side 😅).

Or something like the video recording timer going from top of portrait to top of landscape rather than staying top of portrait when the user changes orientation. 

Thanks for taking the time, really looking forward to using CameraView!

**Comment by FulcrumOne** [comment]
Ohh, I see. I'll try to fix it in this iteration if I still have time (it must be finished by 17 June, as our other libraries are also waiting to be updated 😅).

Thanks again for this finding and I hope you'll find the library useful!

**Comment by jamesbradleym** [comment]
Hey @FulcrumOne - Noticed this was updated as not planned, based on our original discussion it sounded like the implementation of a single view being orientation locked, but not others, was difficult to implement. Was this closed as there's no good way to go about implementing it or was there a different reason? (Curious to know if it's a technical limitation. Thanks!)

**Comment by FulcrumOne** [comment]
Hey @jamesbradleym,

During the previous sprint I tried to achieve the exact results of our discussion, but during testing I noticed a few things that made it too complicated in relation to the potential benefits. 

First of all, I would like to point out that I was able to achieve the desired result, but it was just too disappointing; I started with the most obvious solution, which was to use some low-level language tricks, that worked fine in UIKit, but when I wanted to achieve the same thing in SwiftUI, it was impossible because UIViewController stopped receiving updates in the `viewWillTransition` method 😅

I then tried other options - MotionManager and screen change notifications - but again this was a dead end - it worked, but as I couldn't 'turn off' the screen rotation animation, it just wasn't a good solution, especially as it overcomplicated the code (the part where I had to do extra calculations to get the screen orientation) and would be really tedious for anyone trying to write their own camera screen. 

For the above reasons, I have decided to give up and I'm really sorry for this. As a part of my ‘apologies’, I could give you some hints of how to adjust the UX of your app so it doesn't need this feature 😅 

Best regards,
Tomasz K.

**Comment by jamesbradleym** [comment]
No need to apologize at all! I greatly appreciate the detailed response, this was above and beyond my skillset and my 'working' implementation has the same issue you pointed out with the screen rotation animation. Thanks for taking the time to look in to this so thoroughly 🙏🏼
